# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Unit Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Setup package manager + Install dependencies
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
      - name: Run tests
        run: pnpm test
